// src/lib/pdf/pdf-service.ts
// Server-side PDF generation service using @react-pdf/renderer.

import React from "react";
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { renderToBuffer } = require("@react-pdf/renderer");

/**
 * Renders a React PDF document to a Buffer.
 * Used by API routes to return application/pdf responses.
 */
export async function renderPdfToBuffer(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  document: any
): Promise<Buffer> {
  const arrayBuffer = await renderToBuffer(document);
  return Buffer.from(arrayBuffer);
}

/**
 * Formats a decimal number as BDT currency string.
 */
export function formatBDT(amount: number): string {
  return `৳${amount.toLocaleString("en-BD", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

/**
 * Formats a date as DD/MM/YYYY.
 */
export function formatPdfDate(date: Date | string): string {
  const d = new Date(date);
  return d.toLocaleDateString("en-BD", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  });
}

export const PDF_FOOTER_TEXT = "Generated by VisaTek ERP — Confidential";
export const PDF_PRIMARY_COLOR = "#1e40af";
export const PDF_ACCENT_COLOR  = "#3b82f6";
export const PDF_TEXT_COLOR    = "#1e293b";
export const PDF_MUTED_COLOR   = "#64748b";
export const PDF_BORDER_COLOR  = "#e2e8f0";
export const PDF_BG_LIGHT      = "#f8fafc";
